name: python-deployment
run-name: ${{ github.actor }} - ${{ github.ref_name }} - ${{ github.sha }}

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

env:
  PYTHON_VERSION: 3.8

jobs:
  python-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

        name: Setup Python ${{ env.PYTHON_VERSION }}
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          pip install -r requirements.txt

      - name: Lint
        run: |
          flake8 . --show-source --statistics --exit-zero

      - name: Check complexity
        run: |
          cd ..
          flake8 . --statistics --max-complexity=10 --exit-zero

      - name: Run unit tests
        run: |
          pytest -v --cov=. --cov-report=term-missing

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: src/htmlcov

      - name: Upload Python code as artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-code
          path: src/
